VTM 2024
Dsek-LTH/styrdokument pull request #3
Opened 2024-10-03 15:55 UTC by LeonIngman

Justeringar i våra kära styrdokument efter VTM 2024

2024-10-04 10:49 UTC, fnurkla requested changes

2024-10-04 10:49 UTC, fnurkla commented on reglemente/reglemente.tex
> +	TLTH-Fullmäktige - Tilldelas den som valts in som ordinarie ledamot eller suppleant i Teknologkårens fullmäktige
Jag tror inte att det var meningen att lägga till den första biten i meningen här. Då får man ju det dubbelt i PDF:en:
![image](https://github.com/user-attachments/assets/e9bf760c-eade-42b4-9daf-a7533690c21f)

2024-10-04 13:11 UTC, LeonIngman commented on reglemente/reglemente.tex
> +	TLTH-Fullmäktige - Tilldelas den som valts in som ordinarie ledamot eller suppleant i Teknologkårens fullmäktige
Penis, hur fixar man det här och behåller snygg git historik? Kan jag göra en ny commit där jag fixar det bara?

2024-10-04 14:44 UTC, DagHemberg requested changes
Ser bra ut! Hittade några små grejer, och det verkar också som att uppdateringar i Policy för Tackverksamhet saknas 😶‍🌫️

2024-10-04 14:44 UTC, DagHemberg commented on policyer/policy_for_styrdokument.tex
> +\subsection{Ändring av strukturen}
Borde stå `Ändringar` istället för `Ändring` enligt motion

2024-10-04 14:44 UTC, DagHemberg commented on policyer/policy_for_styrdokument.tex
> +\end{itemize}
lägg till
```latex
\item VTM 2024 (Joel Bäcker, Josefin Wetterstrand, Sean Jentz)
```
eftersom vi godkände andra läsningen för strategiska mål då.

(Verkar dock redan som mycket av den motionen redan är reflekterad i diverse styrdokument?)

2024-10-07 08:09 UTC, LeonIngman commented on policyer/policy_for_styrdokument.tex
> +\subsection{Ändring av strukturen}
fixat!

2024-10-07 08:51 UTC, DagHemberg approved these changes

2024-10-07 10:24 UTC, fnurkla approved these changes

2024-10-07 10:28 UTC, merged