VTM && HTM1
Dsek-LTH/styrdokument pull request #5
Opened 2024-12-08 19:55 UTC by LeonIngman

När PR för VTM gick igenom gjordes det av misstag med merge with **squash**. Vilket jag inte är jättekär i så i den här PR mergar jag VTM ändringarna och HTM1 ändringarna i en merge. Alla VTM ändringar är därav redan reviewade men värt att gå igenom igen om man pallar. Det är fokus på de fyra andra läsningarna i HTM1 i alla fall!

2024-12-08 20:32 UTC, DagHemberg requested changes
Verkar saknas ändringar i `Policy för samverkan med D-chip` (både från `Andra läsningen: D-chip them out` och Emmas prop), samt att `Policy för röstning` ska tas bort.

Annars, LGTM!

2024-12-08 20:58 UTC, LeonIngman commented
@DagHemberg Har tagit bort policyn och lagt till ändringarna för policy för samverkan med dchip! Kika om det ser bra ut!

2024-12-08 21:03 UTC, DagHemberg approved these changes

2024-12-08 21:03 UTC, DagHemberg commented
Ser bra ut!

2024-12-16 12:44 UTC, fnurkla approved these changes
LGTM

2024-12-16 20:42 UTC, merged