HTM-Val 2024
Dsek-LTH/styrdokument pull request #6
Opened 2024-12-18 11:15 UTC by LeonIngman

Under HTM-Val 2024 röstades även två **andra läsningar** igenom, _**Programmästeriet (Centralprocessutskottet)**_ och _**Sloppa lotten vid sluten votering**_. Dessa förändringar ska nu reflekteras i styrdokumenten.

Införande av CPU påverkade: Stadgarna, Reglementet och Policy för Tackverksamhet
Sloppa lotten vid sluten votering påverkade: Stadgarna

OBS många ändringar för CPU och därav ber jag om extra översyn vid godkännande.

2024-12-19 16:20 UTC, DagHemberg requested changes
Det saknas ändringar i Policy för Val! 

Det saknas också en ändring i Reglementet under Styrelsen -> Sammankomst som säger att Processmästare ska vara ständigt adjungerad på Styrelsemöten som saknas, men förstår nog varför den missades: jag glömde själv ha med den ändringen i min [uppdaterade diff-bilaga](https://minio.api.dsek.se/documents/public/2024/HTM-val/Bilaga_Reglemente_CPU.pdf) inför HTM-val, men vi röstade fortfarande igenom det under HTM1. Se [diff-bilaga från HTM1](https://minio.api.dsek.se/documents/public/2024/HTM1/Bilaga_Programmasteriet_Uppdaterat_Reglemente.pdf) (fast ändra Programmästare -> Processmästare)

Hittade även några andra småsaker som jag kommenterat.

2024-12-19 16:20 UTC, DagHemberg commented on reglemente/reglemente.tex
> +                \item tillgodose övriga programmerings- och teknikprojekt tackevenemang
stryk tackevenemang

2024-12-19 16:20 UTC, DagHemberg commented on reglemente/reglemente.tex
> +        Det åligger Processmästare
Processmästare -> Processmästaren

2024-12-19 16:20 UTC, DagHemberg commented on reglemente/reglemente.tex
> +        Det åligger Vice Processmästare
Vice Processmästare -> Vice Processmästaren

2024-12-19 16:22 UTC, DagHemberg commented on reglemente/reglemente.tex
> +        Det åligger Vice Processmästare
plus (som jag märkte nu):
- Vice programmästaren / programmästaren -> Vice Processmästaren / Processmästaren
- Webbmästarens -> DWWW-ansvarigs
- Systemmästarens -> roots

2025-01-28 16:09 UTC, LeonIngman commented on reglemente/reglemente.tex
> +                \item tillgodose övriga programmerings- och teknikprojekt tackevenemang
Löst!

2025-01-28 16:14 UTC, LeonIngman commented on reglemente/reglemente.tex
> +        Det åligger Vice Processmästare
Hittade en till programmästeriet, ändrar den också

2025-01-28 17:01 UTC, LollaSH commented
@DagHemberg Tjena, Jag och Leon (mest Leon) har fixat det här nu. Kika och se vad du tycker! :)

2025-02-10 20:43 UTC, DagHemberg approved these changes

2025-02-10 20:50 UTC, merged